spring.application.name=encurtador-url

# ===============================
# 1. CONFIGURAÇÕES DO POSTGRESQL (Banco Relacional)
# ===============================
# MUDAMOS DE 5432 PARA 5433!
spring.datasource.url=jdbc:postgresql://localhost:5433/encurtador_db
spring.datasource.username=admin
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# 2. CONFIGURAÇÕES DO JPA / HIBERNATE
# ===============================
# O 'update' faz o Spring criar a tabela 'urls' automaticamente no banco assim que rodar!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ===============================
# 3. CONFIGURAÇÕES DO REDIS (Nosso Cache Ultrarrápido)
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379
